# Definiere die Symbole die verwendet werden:
filterOff = "mdi:filter-off"
edit = "mdi:edit"
add = "mdi:add"
delete = "mdi:delete"
save = "mdi:content-save"
databaseSearch = "mdi:database-search"
download = "mdi:import"
close = "mdi:close"
refresh = "mdi:refresh"
today = "mdi:target-arrow"
settings = "mdi:cog"
error = "mdi:error-outline"
check = "mdi:check-circle-outline"
